[package]
name = "lg-gram-settings"
version = "0.5.0"
edition = "2024"

[dependencies]
adw = { version = "0.7", package = "libadwaita", features = ["v1_7"] }
gtk = { version = "0.9", package = "gtk4", features = ["v4_18"] }

[build-dependencies]
glib-build-tools = "0.20"
